### ISSUE TITLE
news.barrons() returns empty dataframe

### ISSUE THREAD

**Issue by philsv** [peterlacour/finpie#7]
The examples I tried: XOM, TSLA, GM

Could be something they changed on their website?

**Comment by peterlacour** [comment]
Hey phil, 

it seems to be working fine for me.. It might be an issue with the keyword search when you are instantiating the news class?

This is the code i used to check it with just the tickers as keywords:

```
import finpie as fp

endDate = '2019-01-01'

news = fp.NewsData('XOM', 'xom')
xom_df  = news.barrons(endDate)

news = fp.NewsData('TSLA', 'tsla')
tsla_df  = news.barrons(endDate)

news = fp.NewsData('GM', 'gm')
gm_df = news.barrons(endDate)
```

To get rid of strange articles and weird results you can then further filter the data with the filter function like this:

```
news.filterz = [ 'exxon', 'mobil', 'oil', 'energy' ]
xom_df = news.filter_data(xom_df)
```

Right now the filter function looks for keywords in both the headline and the description and filters out the rest but will also add an option to decide on whether to just filter the headline, description or both.

Rather than using the barrons "company sites" (like this one https://www.barrons.com/quote/stock/tsla) I used the actual search function for barrons to look for articles which can yield some strange results depending on the keywords. There was a reason why I preferred the other one but I can adjust that and make that an option as well. 

I have been a bit busy but should be able to add this stuff this weekend.

Let me know if this helps

**Comment by philsv** [comment]
It's actually working. I was using: from finpie import NewsData. This worked for me with seeking alpha but seemed to be an issue with Barron's. Thanks!
