### ISSUE TITLE
Issue with news.seeking_alpha(press_releases=True) Non-Scrolling Press Releases

### ISSUE THREAD

**Issue by philsv** [peterlacour/finpie#8]
Hi Peter,

there seems to be a problem with seeking alpha when there are too few news or press releases available.

Here is an example: https://seekingalpha.com/symbol/SCHN/press-releases

The script keeps on running: "checking for service worker update..."

Maybe this can be fixed with try except?

**Comment by peterlacour** [comment]
Hi phil,

I am not sure what the issue is as I can't seem to replicate the issue with this code:

```
news = NewsData('SCHN', '')
df_news = news.seeking_alpha()
df_press_releases = news.seeking_alpha(press_releases = True)
```

The only thing I could think of right now is that this somehow has something to do with a different screen resolution on your side although I am not sure that should have any effect. It could also be related to the number of requests you are running on the website.. Do you maybe have another example?

The seeking alpha scrape is quite inefficient though anyways and will fix that this evening.

**Comment by philsv** [comment]
Hi Peter,

I do not have another example. I do have a different screen resolution but this is the only stock that this kind of issue happened to me. If I find another example I will forward it to you. I think the issue can be closed for now.
